import java.util.Scanner;
import java.util.Random;
public class GiocoLotto {
    public static void main(String[] Args) {
        //variable declaration
        int scelta, dim = 0;
        double puntata1 = 0, puntata2 = 0, puntata3 = 0, puntata4 = 0, puntata5 = 0;
        int cont1 = 0, cont2, cont3, cont4, cont5;
        double Vp1, Vp2, Vp3, Vp4, Vp5;
        int sceltapuntata, dimU = 0;
        int costS = 55, costA = 250, costT = 4500, costQ = 120000, costC = 6000000;

        Scanner tastiera = new Scanner(System.in);
        do {

            //menu option
            System.out.println("=== Gioco Lotto === \nSu quante ruote vuoi giocare?\n");
            String[] opzioni = {"[1] Una ruota",
                    "[2] Dieci ruote",};
            scelta = Menu(opzioni, tastiera);

            switch (scelta) {
                case 1: {
                    dim = 5;
                    break;
                }
                case 2: {
                    dim = 50;
                    break;
                }
            }
         /*if the users chooses to play on one wheel, then the size of the array
        becomes five, if he chooses to play on ten wheels it becomes 50
        */
            int[] ruotaN = new int[dim];
            for (int i = 0; i < ruotaN.length; i++) {
                int k, controllo;
                do {
                    controllo = 0;
                    k = numRand(1, 90);
                    for (int j = 0; j < ruotaN.length; j++) {
                        if (ruotaN[j] == k) {
                            controllo++;
                        }
                    }
                } while (controllo == 1);
                ruotaN[i] = k;
            }
            //Where the numbers of the wheels are randomly generated by a random method
            System.out.println("quanti numeri vuoi inserire? da 1 a 5");
            do {
                dimU = tastiera.nextInt();
            } while (dimU < 1 || dimU > 5);
            int[] NumUtente = new int[dimU];
            System.out.println("Gioca i numeri");
            for (int i = 0; i < NumUtente.length; i++) {
                do {
                    int k, controllo;
                    do {
                        controllo = 0;
                        k = tastiera.nextInt();
                        for (int j = 0; j < NumUtente.length; j++) {
                            if (NumUtente[j] == k) {
                                System.out.println("hai gia inserito questo numero!");
                                controllo++;
                            }
                        }
                    } while (controllo == 1);
                    NumUtente[i] = k;
                    if (NumUtente[i] < 1 || NumUtente[i] > 90) {
                        System.out.println("Hai inserito un valore errato!!");
                    }
                } while (NumUtente[i] < 1 || NumUtente[i] > 90);
            }
            //Where the User choose and insert the numbers that he/she choose and bets on
            boolean s1 = false, s2 = false, s3 = false, s4 = false, s5 = false;
            do {
                System.out.println("----Scegli su cosa puntare----");
                if (dimU >= 1) {
                    System.out.println("[1] Singolo");
                    if (dimU >= 2) {
                        System.out.println("[2] Ambo");
                        if (dimU >= 3) {
                            System.out.println("[3] Terna");
                            if (dimU >= 4) {
                                System.out.println("[4] Quaterna");
                                if (dimU >= 5) {
                                    System.out.println("[5] Cinquina");
                                }
                            }
                        }
                    }
                }
                //Where The user chose where he/she wants to bet
                System.out.println("[0] esci");
                sceltapuntata = tastiera.nextInt();
                switch (sceltapuntata) {
                    case 1: {
                        if (s1 == false) {
                            System.out.println("Hai scelto di puntare su singolo!");
                            s1 = true;
                            do {
                                System.out.println("Quanto vuoi puntare??");
                                puntata1 = 0;
                                puntata1 = tastiera.nextDouble();
                            } while (puntata1 < 0.50 || puntata1 > 200);
                        } else if (s1 == true) {
                            System.out.println("Hai Gia scelto singolo");

                        }
                        break;
                    }
                    case 2: {
                        if (dimU > 1) {
                            if (s2 == false) {
                                System.out.println("Hai scelto di puntare su ambo!");
                                s2 = true;
                                do {
                                    System.out.println("Quanto vuoi puntare??");
                                    puntata2 = 0;
                                    puntata2 = tastiera.nextDouble();
                                } while (puntata2 < 0.50 || puntata2 > 200);
                            } else if (s2 == true) {
                                System.out.println("Hai Gia scelto ambo");
                            }
                        }

                        break;
                    }
                    case 3: {
                        if (dimU > 2) {
                            if (!s3) {
                                System.out.println("Hai scelto di puntare su terna!");
                                s3 = true;
                                do {
                                    System.out.println("Quanto vuoi puntare??");
                                    puntata3 = 0;
                                    puntata3 = tastiera.nextDouble();
                                } while (puntata3 < 0.50 || puntata3 > 200);
                            } else if (s3) {
                                System.out.println("Hai Gia scelto terna");
                            }
                        }
                        break;
                    }
                    case 4: {
                        if (!s4) {
                            System.out.println("Hai scelto di puntare su quaterna!");
                            s4 = true;
                            do {
                                System.out.println("Quanto vuoi puntare??");
                                puntata4 = 0;
                                puntata4 = tastiera.nextDouble();
                            } while (puntata4 < 0.50 || puntata4 > 200);
                        } else if (s4) {
                            System.out.println("Hai Gia scelto quaterna");
                        }
                        break;
                    }
                    case 5: {
                        if (!s5) {
                            System.out.println("Hai scelto di puntare su cinquina!");
                            s5 = true;
                            do {
                                System.out.println("Quanto vuoi puntare??");
                                puntata5 = 0;
                                puntata5 = tastiera.nextDouble();
                            } while (puntata5 < 0.50 || puntata5 > 200);
                        } else if (s5) {
                            System.out.println("Hai Gia scelto cinquina");
                        }
                        break;
                    }
                }
            } while (sceltapuntata != 0);
            //Where the programm check what you choose and how much you bet on it and checks if you putted more than 0.50$ or less than 200$
            for (int i = 0; i < NumUtente.length; i++) {
                for (int k = 0; k < ruotaN.length; k++) {
                    if (NumUtente[i] == ruotaN[k]) {
                        cont1++;
                    }
                }
            }
            System.out.println("singoli fatti:" + cont1);
            if (s2) {
                cont2 = getFactorial(cont1) / (getFactorial(2) * getFactorial((cont1 - 2)));
                System.out.println("Ambo fatti:" + cont2);
            }
            if (s3) {
                cont3 = getFactorial(cont1) / (getFactorial(3) * getFactorial((cont1 - 3)));
                System.out.println("terni fatti:" + cont3);
            }
            if (s4) {
                cont4 = getFactorial(cont1) / (getFactorial(4) * getFactorial((cont1 - 4)));
                System.out.println("quterni fatti:" + cont4);
            }
            if (s5) {
                cont5 = getFactorial(cont1) / (getFactorial(5) * getFactorial((cont1 - 5)));
                System.out.println("cinquine fatti:" + cont5);
            }
            Vp1 = calcoloVincita(dim, costS, puntata1) - puntata1;
            Vp2 = calcoloVincita(dim, costA, puntata2) - puntata2;
            Vp3 = calcoloVincita(dim, costT, puntata3) - puntata3;
            Vp4 = calcoloVincita(dim, costQ, puntata4) - puntata4;
            Vp5 = calcoloVincita(dim, costC, puntata5) - puntata5;
            double vincitacomp = Vp1 + Vp2 + Vp3 + Vp4 + Vp5;
            System.out.println("Soldi vinti: " + vincitacomp + "$\n");
            //The calculation of the complessive money won or lost
            System.out.println("Vuoi continuare a giocare?");
            System.out.println("[1]Si\n[2]no");
            scelta = tastiera.nextInt();
            //gives the user the chance to replay the program
        }while(scelta!=2);
    }

    private static int Menu(String opzioni[], Scanner tastiera) {
        int scelta;

        do {

            System.out.println(opzioni[0]);
            for (int i = 1; i < opzioni.length; i++) {
                System.out.println(opzioni[i]);
            }
            scelta = tastiera.nextInt();

            if ((scelta < 1) || (scelta > opzioni.length - 1)) {
                System.out.println("Opzione Sbagliata");
                Wait();
                ClrScr();


            }
        }
        while ((scelta < 1) || (scelta > opzioni.length - 1));

        return scelta;
    }

    //Random number generator method from 1 to 90
    private static int numRand(int minValue, int maxValue) {

        Random num = new Random();
        return num.nextInt(maxValue) + minValue;

    }

    //Method to delete the screen
    private static void ClrScr() {
        try {
            new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    //Method to wait a certain amount of time
    private static void Wait() {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
    //method to calculate the factorial of a number
    public static int getFactorial(int Fact) {
        int result = 1;
        for (int i = 1; i <= Fact; i++) {
            result = result * i;
        }
        return result;
    }
    //Method to find how much you won by betting
    public static double calcoloVincita(int NumR, int Cost, double puntata) {
        double vincita;
        vincita = (puntata * Cost) / NumR;
        return vincita;
    }

}